"""Click-to-run GUI for the YouTube Guitar Tab Parser.

Paste a YouTube URL and press Generate. A window then asks you to drag a box
around the tab area on one frame; the app crops every frame to that box, removes
duplicate/blank/overlapping lines (or stitches a sideways-scrolling tab), and
saves a PDF named after the video into a `tabs` folder next to the app (existing
files there are left untouched). All intermediate files (video, frames, cropped
images) are deleted automatically.

Packaged into a single-file app with PyInstaller (see build_windows.bat for
Windows, build_mac.sh for macOS), so the person you share it with does not
need Python or any setup.
"""

import os
import re
import subprocess
import sys
import tempfile
import threading
import traceback
import shutil

try:
    import winsound  # Windows only; used for the "your turn" chime
except ImportError:
    winsound = None

import tkinter as tk
from tkinter import ttk, filedialog, messagebox
from PIL import Image, ImageEnhance, ImageTk

from clear_files import clear_all
from download_frames import download
from extract_tab_pics import extract_tab
from clean_tab import make_pdf
import ytdlp_runtime
from version import APP_VERSION

# build_config.py is generated by the build scripts / CI: release builds get
# IS_RELEASE = True (no Details log box; logs go to a file instead), dev builds
# and source runs stay verbose.
try:
    from build_config import IS_RELEASE
except ImportError:
    IS_RELEASE = False


def app_base_dir():
    """Folder the app lives in: next to the .exe on Windows, next to the .app
    bundle on macOS, else the source dir.

    On Windows, sys.executable is the .exe itself, so its directory is already
    "next to the app". On macOS, PyInstaller's --windowed build is wrapped in a
    GuitarTabParser.app bundle, so sys.executable actually points three levels
    deep inside it (GuitarTabParser.app/Contents/MacOS/GuitarTabParser) -- using
    its directory as-is would put the `tabs` folder inside the bundle instead of
    next to it. Climb out of the bundle so it lands beside the .app, matching
    Windows behavior and what the README promises.
    """
    if getattr(sys, "frozen", False):
        exe_dir = os.path.dirname(os.path.abspath(sys.executable))
        if sys.platform == "darwin":
            parts = exe_dir.split(os.sep)
            for i, part in enumerate(parts):
                if part.endswith(".app"):
                    return os.sep.join(parts[:i]) or os.sep
        return exe_dir
    return os.path.dirname(os.path.abspath(__file__))


def _writable_dir(path):
    """True if `path` exists (or can be created) and we can write into it."""
    try:
        os.makedirs(path, exist_ok=True)
        probe = os.path.join(path, ".write-test")
        with open(probe, "w"):
            pass
        os.remove(probe)
        return True
    except OSError:
        return False


def default_output_dir():
    """Finished PDFs are collected in a `tabs` folder next to the app.

    On macOS, Gatekeeper runs an unsigned app downloaded from the internet from
    a random read-only copy ("App Translocation", a path under
    /private/var/folders/.../AppTranslocation/). "Next to the app" is then not
    writable, so fall back to ~/Documents/GuitarTabParser/tabs. The same
    fallback covers a read-only install location on any platform.
    """
    preferred = os.path.join(app_base_dir(), "tabs")
    if "/AppTranslocation/" not in preferred and _writable_dir(preferred):
        return preferred
    return os.path.join(os.path.expanduser("~"), "Documents", "GuitarTabParser", "tabs")


def safe_filename(name):
    """Turns a video title into a valid filename (Windows and macOS)."""
    name = re.sub(r'[\\/:*?"<>|]+', "", name or "").strip()
    name = re.sub(r"\s+", " ", name)
    return name[:120] or "tab"


def unique_path(path):
    """Returns `path`, or `path (2)`, `path (3)`, ... if it already exists."""
    if not os.path.exists(path):
        return path
    root, ext = os.path.splitext(path)
    i = 2
    while os.path.exists(f"{root} ({i}){ext}"):
        i += 1
    return f"{root} ({i}){ext}"


def setup_entry_clipboard(entry):
    """Makes copy/paste work reliably in an Entry, plus a right-click menu.

    In the PyInstaller-packaged app on macOS, Cmd+V only flashes the Edit menu:
    the accelerator fires but the <<Paste>> virtual event never reaches the
    focused widget, so nothing is inserted. Bind the shortcuts straight to the
    entry (returning "break" so a working default doesn't run twice), and give
    every platform a right-click Cut/Copy/Paste/Select-All menu as a
    keyboard-free fallback.
    """

    def paste(event=None):
        try:
            text = entry.clipboard_get()
        except tk.TclError:
            return "break"   # clipboard empty or not text
        try:
            entry.delete("sel.first", "sel.last")
        except tk.TclError:
            pass             # no selection
        entry.insert("insert", text)
        return "break"

    def copy(event=None):
        try:
            text = entry.selection_get()
        except tk.TclError:
            return "break"   # no selection
        entry.clipboard_clear()
        entry.clipboard_append(text)
        return "break"

    def cut(event=None):
        copy()
        try:
            entry.delete("sel.first", "sel.last")
        except tk.TclError:
            pass
        return "break"

    def select_all(event=None):
        entry.select_range(0, "end")
        entry.icursor("end")
        return "break"

    accel = "Command" if sys.platform == "darwin" else "Control"
    for key, handler in (("v", paste), ("c", copy), ("x", cut), ("a", select_all)):
        entry.bind(f"<{accel}-{key}>", handler)
        entry.bind(f"<{accel}-{key.upper()}>", handler)   # Caps Lock / Shift held

    menu = tk.Menu(entry, tearoff=0)
    menu.add_command(label="Cut", command=cut)
    menu.add_command(label="Copy", command=copy)
    menu.add_command(label="Paste", command=paste)
    menu.add_separator()
    menu.add_command(label="Select All", command=select_all)

    def popup(event):
        entry.focus_set()
        menu.tk_popup(event.x_root, event.y_root)
        return "break"

    # Button-2/-3 cover right-click across platforms; Control-click is the
    # macOS trackpad convention.
    entry.bind("<Button-2>", popup)
    entry.bind("<Button-3>", popup)
    if sys.platform == "darwin":
        entry.bind("<Control-Button-1>", popup)


class RegionSelector(tk.Toplevel):
    """Modal window: user drags a rectangle over the tab area of one frame.

    Returns bounds as (y1, x1, y2, x2) in the original image's pixel coordinates,
    matching region_selector.prompt_coords so extract_tab can use it unchanged.
    """

    MIN_BOX = 10          # display pixels; smaller is a stray click, not a drag
    DIM = 0.35            # brightness of the area that will be cut away

    def __init__(self, master, image_path, on_done):
        super().__init__(master)
        self.title("Select the tab area")
        self.on_done = on_done
        self._sent = False

        img = Image.open(image_path)
        max_w, max_h = 1100, 680
        self.scale = min(max_w / img.width, max_h / img.height, 1.0)
        self._bright = img.resize((max(1, int(img.width * self.scale)),
                                   max(1, int(img.height * self.scale))))
        self._img_w, self._img_h = self._bright.size

        # Two copies of the frame: the real one, and a darkened one. Before any
        # drag the bright copy is shown so the tab is easy to read. Once a box
        # exists the dark copy becomes the background and only the box is drawn
        # bright on top, so what will be kept is obvious at a glance.
        self._tk_bright = ImageTk.PhotoImage(self._bright)
        self._tk_dim = ImageTk.PhotoImage(
            ImageEnhance.Brightness(self._bright).enhance(self.DIM))
        self._tk_reveal = None

        head = ttk.Frame(self, padding=(10, 8, 10, 2))
        head.pack(fill="x")
        tk.Label(head, text="Drag a box around the tab",
                 font=("Segoe UI", 13, "bold"), anchor="w").pack(fill="x")
        tk.Label(head, text="Anything left dark is cut away.",
                 anchor="w", justify="left", fg="#555555").pack(fill="x")

        self.canvas = tk.Canvas(self, width=self._img_w, height=self._img_h,
                                cursor="cross", highlightthickness=0)
        self.canvas.pack(padx=10, pady=6)
        self._base = self.canvas.create_image(0, 0, anchor="nw", image=self._tk_bright)
        self._rect = None
        self._reveal = None
        self._start = (0, 0)
        self._box = None
        self._redraw_pending = False

        # A hint sitting on the image itself, where the user has to act. It goes
        # away for good on the first press.
        self._hint = self._make_hint()

        self.canvas.bind("<ButtonPress-1>", self._press)
        self.canvas.bind("<B1-Motion>", self._drag)
        self.canvas.bind("<ButtonRelease-1>", self._drag)

        # height=1 reserves the line even while the text is empty, so the
        # window does not jump the moment the first size appears.
        self.size_var = tk.StringVar(value="")
        tk.Label(self, textvariable=self.size_var, fg="#555555", height=1).pack()

        bar = ttk.Frame(self, padding=8)
        bar.pack()
        self.confirm_btn = ttk.Button(bar, text="Confirm", command=self._confirm,
                                      state="disabled")
        self.confirm_btn.pack(side="left", padx=5)
        ttk.Button(bar, text="Cancel", command=self._cancel).pack(side="left", padx=5)

        self.bind("<Return>", lambda e: self._confirm())
        self.bind("<Escape>", lambda e: self._cancel())

        self.protocol("WM_DELETE_WINDOW", self._cancel)
        self.transient(master)
        self.grab_set()
        self.resizable(False, False)

    def _make_hint(self):
        """Text over the middle of the image telling the user what to do."""
        cx, cy = self._img_w // 2, self._img_h // 2
        text = self.canvas.create_text(cx, cy, text="Click and drag across the tab",
                                       fill="#ffffff", font=("Segoe UI", 14, "bold"))
        x0, y0, x1, y1 = self.canvas.bbox(text)
        pad = 12
        box = self.canvas.create_rectangle(x0 - pad, y0 - pad, x1 + pad, y1 + pad,
                                           fill="#1c1c1c", outline="#12b886", width=2)
        self.canvas.tag_raise(text, box)   # keep the text above its backing box
        return (box, text)

    def _clear_hint(self):
        if self._hint:
            for item in self._hint:
                self.canvas.delete(item)
            self._hint = None

    def _clamp(self, x, y):
        return (max(0, min(int(x), self._img_w - 1)),
                max(0, min(int(y), self._img_h - 1)))

    def _press(self, e):
        self._clear_hint()
        self._start = self._clamp(e.x, e.y)
        self.canvas.itemconfig(self._base, image=self._tk_dim)
        if self._rect:
            self.canvas.delete(self._rect)
        x, y = self._start
        self._rect = self.canvas.create_rectangle(x, y, x, y, outline="#12b886", width=2)
        self._drag(e)

    def _drag(self, e):
        if not self._rect:
            return
        x, y = self._clamp(e.x, e.y)
        x0, x1 = sorted((self._start[0], x))
        y0, y1 = sorted((self._start[1], y))
        self._box = (x0, y0, x1, y1)
        self.canvas.coords(self._rect, x0, y0, x1, y1)

        big_enough = (x1 - x0) >= self.MIN_BOX and (y1 - y0) >= self.MIN_BOX
        self.confirm_btn.config(state="normal" if big_enough else "disabled")
        if big_enough:
            # Report in source-image pixels, which is what actually gets cropped.
            self.size_var.set("Box: %d x %d px"
                              % (round((x1 - x0) / self.scale),
                                 round((y1 - y0) / self.scale)))
        else:
            self.size_var.set("Too small -- keep dragging.")
        self._schedule_reveal()

    def _schedule_reveal(self):
        """Repaint the bright cut-out, at most once per idle turn.

        Motion events arrive faster than the image work behind a repaint, so
        coalescing keeps the drag smooth on a large frame.
        """
        if not self._redraw_pending:
            self._redraw_pending = True
            self.after_idle(self._draw_reveal)

    def _draw_reveal(self):
        self._redraw_pending = False
        if not self._box:
            return
        x0, y0, x1, y1 = self._box
        if x1 - x0 < 1 or y1 - y0 < 1:
            return
        crop = self._bright.crop((x0, y0, x1, y1))
        self._tk_reveal = ImageTk.PhotoImage(crop)   # hold a ref or Tk drops it
        if getattr(self, "_reveal", None) is None:
            self._reveal = self.canvas.create_image(x0, y0, anchor="nw",
                                                    image=self._tk_reveal)
        else:
            self.canvas.coords(self._reveal, x0, y0)
            self.canvas.itemconfig(self._reveal, image=self._tk_reveal)
        self.canvas.tag_raise(self._rect, self._reveal)   # outline stays visible

    def _confirm(self):
        if not self._box:
            return
        x0, y0, x1, y1 = self._box
        if x1 - x0 < self.MIN_BOX or y1 - y0 < self.MIN_BOX:
            messagebox.showwarning("Box too small", "Drag a bigger box.")
            return
        self._finish((int(y0 / self.scale), int(x0 / self.scale),
                      int(y1 / self.scale), int(x1 / self.scale)))

    def _cancel(self):
        self._finish(None)

    def _finish(self, bounds):
        if not self._sent:
            self._sent = True
            self.on_done(bounds)
        self.destroy()


class _GuiLog:
    """File-like object that forwards writes to the GUI log, thread-safely."""

    def __init__(self, app):
        self.app = app

    def write(self, msg):
        if msg:
            self.app.append_log(msg)

    def flush(self):
        pass


class App(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title(f"YouTube Guitar Tab Parser v{APP_VERSION}"
                   + ("" if IS_RELEASE else " (dev)"))
        if IS_RELEASE:
            self.geometry("640x300")   # no Details box, so a shorter window
            self.minsize(560, 260)
        else:
            self.geometry("640x520")
            self.minsize(560, 460)

        self._region_bounds = None
        self._region_event = threading.Event()

        pad = {"padx": 12, "pady": 6}

        frm = ttk.Frame(self, padding=12)
        frm.pack(fill="both", expand=True)

        ttk.Label(frm, text="YouTube URL").grid(row=0, column=0, sticky="w")
        self.url_var = tk.StringVar()
        url_entry = ttk.Entry(frm, textvariable=self.url_var)
        url_entry.grid(row=1, column=0, columnspan=2, sticky="ew", pady=(0, 8))
        setup_entry_clipboard(url_entry)

        ttk.Label(frm, text="Save folder").grid(row=2, column=0, columnspan=2, sticky="w")
        self.out_var = tk.StringVar(value=default_output_dir())
        out_entry = ttk.Entry(frm, textvariable=self.out_var)
        out_entry.grid(row=3, column=0, sticky="ew")
        setup_entry_clipboard(out_entry)
        ttk.Button(frm, text="Browse...", command=self._browse).grid(row=3, column=1, sticky="e", padx=(8, 0))

        self.generate_btn = ttk.Button(frm, text="Generate Tab PDF", command=self._on_generate)
        self.generate_btn.grid(row=4, column=0, columnspan=2, sticky="ew", pady=12)

        # Prominent status line + progress bar (the main "what's happening" cue).
        self.status_var = tk.StringVar(value="Ready")
        self.status_label = tk.Label(frm, textvariable=self.status_var, anchor="w",
                                     font=("Segoe UI", 11, "bold"), fg="#868e96")
        self.status_label.grid(row=5, column=0, columnspan=3, sticky="ew", pady=(6, 2))

        self.progress = ttk.Progressbar(frm, mode="determinate", maximum=100)
        self.progress.grid(row=6, column=0, columnspan=3, sticky="ew", pady=(0, 10))

        # Detailed logs: a visible Details box in dev builds; a plain log file
        # (app-data folder) in release builds, so support questions can still be
        # answered without cluttering the UI.
        self.log_text = None
        self._log_file = None
        if IS_RELEASE:
            try:
                self._log_file = open(os.path.join(ytdlp_runtime.data_dir(), "last-run.log"),
                                      "w", encoding="utf-8", errors="replace")
            except OSError:
                pass
        else:
            ttk.Label(frm, text="Details").grid(row=7, column=0, sticky="w")
            self.log_text = tk.Text(frm, height=9, wrap="word", state="disabled")
            self.log_text.grid(row=8, column=0, columnspan=2, sticky="nsew")
            scroll = ttk.Scrollbar(frm, command=self.log_text.yview)
            scroll.grid(row=8, column=2, sticky="ns")
            self.log_text.configure(yscrollcommand=scroll.set)
            frm.rowconfigure(8, weight=1)

        frm.columnconfigure(0, weight=1)

        # Route every print() (ours and the pipeline's) to the log sink. This also
        # keeps the windowed .exe from crashing on print when there is no console.
        sys.stdout = _GuiLog(self)
        sys.stderr = _GuiLog(self)

        # Keep yt-dlp fresh: check PyPI in the background; a newer version is
        # picked up the next time the app starts.
        ytdlp_runtime.start_background_update(print)

    # ---- logging (safe from any thread) ----
    def append_log(self, msg):
        if self.log_text is not None:
            self.after(0, self._append, msg)
        elif self._log_file is not None:
            try:
                self._log_file.write(msg if msg.endswith("\n") else msg + "\n")
                self._log_file.flush()
            except (OSError, ValueError):
                pass

    def _append(self, msg):
        self.log_text.configure(state="normal")
        self.log_text.insert("end", msg)
        if not msg.endswith("\n"):
            self.log_text.insert("end", "\n")
        self.log_text.see("end")
        self.log_text.configure(state="disabled")

    def clear_log(self):
        if self.log_text is not None:
            self.log_text.configure(state="normal")
            self.log_text.delete("1.0", "end")
            self.log_text.configure(state="disabled")

    # ---- status + progress (safe from any thread) ----
    def set_status(self, text, color="#1c7ed6"):
        self.after(0, lambda: (self.status_var.set(text), self.status_label.config(fg=color)))

    def set_progress(self, pct):
        """pct in 0..100 shows an exact bar; None shows a busy (animated) bar."""
        def apply():
            if pct is None:
                self.progress.config(mode="indeterminate")
                self.progress.start(12)
            else:
                self.progress.stop()
                self.progress.config(mode="determinate")
                self.progress["value"] = max(0, min(100, pct))
        self.after(0, apply)

    def play_alert(self):
        try:
            if winsound:
                winsound.MessageBeep(winsound.MB_ICONASTERISK)
        except Exception:
            pass

    # ---- region selection bridge (worker thread -> main-thread dialog) ----
    def select_region(self, image_path):
        self._region_bounds = None
        self._region_event.clear()
        self.set_status("👉 Drag a box around the tab in the pop-up", "#e8590c")
        self.after(0, lambda: self._open_region(image_path))
        self._region_event.wait()
        if self._region_bounds is None:
            raise RuntimeError("Tab area selection was cancelled.")
        return self._region_bounds

    def _open_region(self, image_path):
        self.play_alert()  # small chime so the user notices the pop-up
        RegionSelector(self, image_path, on_done=self._on_region_done)

    def _on_region_done(self, bounds):
        self._region_bounds = bounds
        self._region_event.set()

    def _browse(self):
        chosen = filedialog.askdirectory(initialdir=self.out_var.get() or os.path.expanduser("~"))
        if chosen:
            self.out_var.set(chosen)

    def _on_generate(self):
        url = self.url_var.get().strip()
        if not url:
            messagebox.showwarning("Missing URL", "Paste a YouTube URL first.")
            return
        base = self.out_var.get().strip() or default_output_dir()
        if not _writable_dir(base):
            messagebox.showerror(
                "Cannot write to the save folder",
                f"Cannot write to:\n\n{base}\n\nPick another folder with Browse.")
            return
        self.clear_log()                 # wipe the previous run's messages
        self.set_progress(0)
        self.generate_btn.config(state="disabled", text="Working…")
        threading.Thread(target=self._run, args=(url, base), daemon=True).start()

    def _run(self, url, out_dir):
        # All the messy intermediate files (video, frames, cropped images) go in a
        # throwaway system-temp folder -- never inside out_dir -- so the user's
        # existing files in out_dir are never cleared or touched.
        work = tempfile.mkdtemp(prefix="guitartab_")
        try:
            os.makedirs(out_dir, exist_ok=True)
            clear_all(work)

            self.set_status("⬇  Downloading video…")
            self.set_progress(0)
            title = download(work, url, on_progress=self.set_progress)

            # select_region sets its own status + chime and blocks for the user.
            extract_tab(work, select_region=self.select_region)

            self.set_status("🛠  Building PDF…")
            self.set_progress(None)
            print("Removing duplicate, blank and overlapping lines...")
            make_pdf(work)

            # A unique name means we only ever ADD to out_dir, never overwrite.
            final_pdf = unique_path(os.path.join(out_dir, safe_filename(title) + " tab.pdf"))
            shutil.copyfile(os.path.join(work, "output.pdf"), final_pdf)

            print(f"Saved: {final_pdf}")
            self.after(0, lambda: self._finish_ok(final_pdf))
        except (ValueError, TimeoutError) as e:
            # Expected, understandable problems (too long, timed out, live, ...).
            msg = str(e)
            print("⚠ " + msg)
            self.set_status("❌  " + msg[:70], "#e03131")
            self.set_progress(0)
            self.after(0, lambda m=msg: messagebox.showerror("Cannot process this video", m))
        except Exception as e:
            msg = str(e)
            print("ERROR: " + msg)
            print(traceback.format_exc())
            self.set_status("❌  Error", "#e03131")
            self.set_progress(0)
            self.after(0, lambda m=msg: messagebox.showerror("Something went wrong", m))
        finally:
            shutil.rmtree(work, ignore_errors=True)
            self.after(0, lambda: self.generate_btn.config(state="normal", text="Generate Tab PDF"))

    def _finish_ok(self, pdf_path):
        self.progress.stop()
        self.progress.config(mode="determinate")
        self.progress["value"] = 100
        self.set_status("✅  Saved: " + os.path.basename(pdf_path), "#2f9e44")
        try:
            if sys.platform == "win32":
                os.startfile(pdf_path)
            elif sys.platform == "darwin":
                subprocess.run(["open", pdf_path])
            else:
                subprocess.run(["xdg-open", pdf_path])
        except Exception:
            pass
        messagebox.showinfo("Done", f"Saved:\n\n{pdf_path}")


def _selftest():
    """Verify the packaged exe is complete. Optionally decode a video file passed
    after --selftest, to confirm OpenCV's bundled FFmpeg backend works when frozen."""
    import cv2, numpy, PIL  # noqa: F401
    yt_dlp = ytdlp_runtime.get_ytdlp()   # exercises the wheel loader when frozen
    print(f"yt-dlp: {ytdlp_runtime.current_version()}")
    videos = [a for a in sys.argv[1:] if a.lower().endswith((".mp4", ".webm", ".mkv", ".mov"))]
    if videos:
        cap = cv2.VideoCapture(videos[0])
        opened = cap.isOpened()
        got, _ = cap.read() if opened else (False, None)
        cap.release()
        print(f"video-decode: opened={opened} read_frame={got}")
        return 0 if (opened and got) else 2
    print("selftest ok")
    return 0


def _downloadtest():
    """Diagnostic: `--downloadtest <url>` downloads a video through the full
    runtime-loaded yt-dlp path and reports success. Exercises everything the
    packaged app needs for a real download (loader, HTTP backends, extractors)
    without opening the GUI."""
    url = sys.argv[sys.argv.index("--downloadtest") + 1]
    work = tempfile.mkdtemp(prefix="gtp_dltest_")
    try:
        from download_frames import download_youtube_video
        path, title = download_youtube_video(url, work)
        size = os.path.getsize(path)
        print(f"download ok: {title!r} -> {size} bytes")
        return 0 if size > 0 else 2
    finally:
        shutil.rmtree(work, ignore_errors=True)


if __name__ == "__main__":
    if "--selftest" in sys.argv:
        sys.exit(_selftest())
    if "--downloadtest" in sys.argv:
        sys.exit(_downloadtest())
    App().mainloop()
